ProjektKoncowy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='base.html'), name='base'),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

movies/urls.py
from django.urls import path
from movies.views import *

urlpatterns = [
    path('', home, name='home'),
    path('movies/', MovieListView.as_view(), name='movie_list'),
    path('movies/<int:pk>/', MovieDetailView.as_view(), name='movie_detail'),
    path('movies/add/', MovieCreateView.as_view(), name='movie_add'),
    path('movies/<int:pk>/edit/', MovieUpdateView.as_view(), name='movie_edit'),
    path('movies/<int:pk>/delete/', MovieDeleteView.as_view(), name='movie_delete'),

    path('genres/', GenreListView.as_view(), name='genre_list'),
    path('genres/add/', GenreCreateView.as_view(), name='genre_add'),
    path('genres/<int:pk>/edit/', GenreUpdateView.as_view(), name='genre_edit'),
    path('genres/<int:pk>/delete/', GenreDeleteView.as_view(), name='genre_delete'),

    path('persons/', PersonListView.as_view(), name='person_list'),
    path('persons/add/', PersonCreateView.as_view(), name='person_add'),
    path('persons/<int:pk>/edit/', PersonUpdateView.as_view(), name='person_edit'),
    path('persons/<int:pk>/delete/', PersonDeleteView.as_view(), name='person_delete'),
    path('persons/<int:pk>/', PersonDetailView.as_view(), name='person_detail'),

    path('casts/add/', CastCreateView.as_view(), name='cast_add'),
    path('casts/<int:pk>/edit/', CastUpdateView.as_view(), name='cast_edit'),
    path('casts/<int:pk>/delete/', CastDeleteView.as_view(), name='cast_delete'),

    path('awards/', AwardListView.as_view(), name='award_list'),
    path('awards/add/', AwardCreateView.as_view(), name='award_add'),
    path('awards/<int:pk>/edit/', AwardUpdateView.as_view(), name='award_edit'),
    path('awards/<int:pk>/delete/', AwardDeleteView.as_view(), name='award_delete'),
    path('awards/<int:pk>/', AwardDetailView.as_view(), name='award_detail'),

    path('movie_awards/add/', MovieAwardCreateView.as_view(), name='movie_award_add'),
    path('movie_awards/<int:pk>/delete/', MovieAwardDeleteView.as_view(), name='movie_award_delete'),

    path('reviews', ReviewListView.as_view(), name='review_list'),
    path('add/', ReviewCreateView.as_view(), name='review_add'),
    path('<int:pk>/edit/', ReviewUpdateView.as_view(), name='review_edit'),
    path('<int:pk>/delete/', ReviewDeleteView.as_view(), name='review_delete'),
]

movies/models.py
from django.db import models
from django.contrib.auth.models import User


class Genre(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Person(models.Model):
    ACTOR = 'actor'
    DIRECTOR = 'director'
    BOTH = 'both'
    ROLE_CHOICES = [
        (ACTOR, 'Actor'),
        (DIRECTOR, 'Director'),
        (BOTH, 'Both'),
    ]

    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    birth_date = models.DateField()
    death_date = models.DateField(null=True, blank=True)
    role = models.CharField(max_length=10, choices=ROLE_CHOICES, default=ACTOR)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Movie(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    release_year = models.PositiveIntegerField()
    duration_minutes = models.PositiveIntegerField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    directors = models.ManyToManyField(Person, related_name='directed_movies',
                                       limit_choices_to={'role__in': ['director', 'both']})

    def __str__(self):
        return f"{self.title} ({self.release_year})"


class Cast(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    person = models.ForeignKey(Person, on_delete=models.CASCADE, limit_choices_to={'role__in': ['actor', 'both']})
    role_name = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.person} as {self.role_name} in {self.movie}"


class Award(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class MovieAward(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    award = models.ForeignKey(Award, on_delete=models.CASCADE)
    category = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.movie} - {self.award} ({self.category})"


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(choices=[(i, str(i)) for i in range(1, 11)])
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Review of {self.movie} by {self.user}'

movies/forms.py
from django import forms
from .models import Movie, Genre, Person, Cast, Award, MovieAward, Review


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['title', 'description', 'release_year', 'duration_minutes', 'genre', 'directors']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Tytuł'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Opis...'}),
            'release_year': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Rok wydania'}),
            'duration_minutes': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Czas trwania'}),
            'genre': forms.Select(attrs={'class': 'form-control', 'placeholder': 'Gatunek'}),
            'directors': forms.SelectMultiple(attrs={'class': 'form-control'}),
        }


class GenreForm(forms.ModelForm):
    class Meta:
        model = Genre
        fields = ['name']


class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ['first_name', 'last_name', 'birth_date', 'death_date', 'role']


class CastForm(forms.ModelForm):
    class Meta:
        model = Cast
        fields = ['movie', 'person', 'role_name']


class AwardForm(forms.ModelForm):
    class Meta:
        model = Award
        fields = ['name']


class MovieAwardForm(forms.ModelForm):
    class Meta:
        model = MovieAward
        fields = ['award', 'category']


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['movie', 'rating', 'text']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

movies/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Movie, Genre, Person, Cast, Award, MovieAward, Review
from .forms import MovieForm, GenreForm, PersonForm, CastForm, AwardForm, MovieAwardForm, ReviewForm
import logging


class MovieListView(ListView):
    model = Movie
    template_name = 'movies/movie_list.html'
    context_object_name = 'movies'

    def get_queryset(self):
        queryset = self.request.GET.get('q')
        if queryset:
            return Movie.objects.filter(title__icontains=queryset)
        return Movie.objects.all()


class MovieDetailView(DetailView):
    model = Movie
    template_name = 'movies/movie_detail.html'
    context_object_name = 'movie'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['reviews'] = Review.objects.filter(movie=self.object)
        return context


class MovieCreateView(LoginRequiredMixin, CreateView):
    model = Movie
    form_class = MovieForm
    template_name = 'movies/movie_form.html'
    success_url = reverse_lazy('movie_list')


class MovieUpdateView(LoginRequiredMixin, UpdateView):
    model = Movie
    form_class = MovieForm
    template_name = 'movies/movie_form.html'
    success_url = reverse_lazy('movie_list')


class MovieDeleteView(LoginRequiredMixin, DeleteView):
    model = Movie
    template_name = 'movies/movie_confirm_delete.html'
    success_url = reverse_lazy('movie_list')


logger = logging.getLogger(__name__)


class CastCreateView(LoginRequiredMixin, CreateView):
    model = Cast
    form_class = CastForm
    template_name = 'movies/cast_form.html'

    def form_valid(self, form):
        movie_id = self.request.GET.get('movie')
        logger.debug(f"Creating cast for movie ID: {movie_id}")
        form.instance.movie = get_object_or_404(Movie, pk=movie_id)
        return super().form_valid(form)

    def get_success_url(self):
        movie_pk = self.object.movie.pk
        logger.debug(f"Redirecting to movie detail for movie ID: {movie_pk}")
        return reverse_lazy('movie_detail', kwargs={'pk': movie_pk})


class CastUpdateView(LoginRequiredMixin, UpdateView):
    model = Cast
    form_class = CastForm
    template_name = 'movies/cast_form.html'

    def get_success_url(self):
        movie_pk = self.object.movie.pk
        logger.debug(f"Redirecting to movie detail for movie ID: {movie_pk}")
        return reverse_lazy('movie_detail', kwargs={'pk': movie_pk})


class CastDeleteView(LoginRequiredMixin, DeleteView):
    model = Cast
    template_name = 'movies/cast_confirm_delete.html'

    def get_success_url(self):
        movie_pk = self.get_object().movie.pk
        logger.debug(f"Redirecting to movie detail for movie ID: {movie_pk}")
        return reverse_lazy('movie_detail', kwargs={'pk': movie_pk})


class GenreListView(ListView):
    model = Genre
    template_name = 'movies/genre_list.html'
    context_object_name = 'genres'


class GenreCreateView(LoginRequiredMixin, CreateView):
    model = Genre
    form_class = GenreForm
    template_name = 'movies/genre_form.html'
    success_url = reverse_lazy('genre_list')


class GenreUpdateView(LoginRequiredMixin, UpdateView):
    model = Genre
    form_class = GenreForm
    template_name = 'movies/genre_form.html'
    success_url = reverse_lazy('genre_list')


class GenreDeleteView(LoginRequiredMixin, DeleteView):
    model = Genre
    template_name = 'movies/genre_confirm_delete.html'
    success_url = reverse_lazy('genre_list')


class PersonListView(ListView):
    model = Person
    template_name = 'movies/person_list.html'
    context_object_name = 'persons'

    def get_queryset(self):
        query = self.request.GET.get('q')
        role = self.request.GET.get('role')
        queryset = Person.objects.all()
        if role:
            if role == 'actor':
                return Person.objects.filter(role__in=['actor', 'both'])
            elif role == 'director':
                return Person.objects.filter(role__in=['director', 'both'])
        if query:
            queryset = queryset.filter(first_name__icontains=query) | queryset.filter(last_name__icontains=query)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        for person in context['persons']:
            if person.role == 'both':
                person.display_role = 'Actor, Director'
            elif person.role == 'actor':
                person.display_role = 'Actor'
            elif person.role == 'director':
                person.display_role = 'Director'
        return context


class PersonCreateView(LoginRequiredMixin, CreateView):
    model = Person
    form_class = PersonForm
    template_name = 'movies/person_form.html'
    success_url = reverse_lazy('person_list')


class PersonUpdateView(LoginRequiredMixin, UpdateView):
    model = Person
    form_class = PersonForm
    template_name = 'movies/person_form.html'
    success_url = reverse_lazy('person_list')


class PersonDeleteView(LoginRequiredMixin, DeleteView):
    model = Person
    template_name = 'movies/person_confirm_delete.html'
    success_url = reverse_lazy('person_list')


class PersonDetailView(DetailView):
    model = Person
    template_name = 'movies/person_detail.html'
    context_object_name = 'person'


class AwardListView(ListView):
    model = Award
    template_name = 'movies/award_list.html'
    context_object_name = 'awards'


class AwardCreateView(LoginRequiredMixin, CreateView):
    model = Award
    form_class = AwardForm
    template_name = 'movies/award_form.html'
    success_url = reverse_lazy('award_list')


class AwardUpdateView(LoginRequiredMixin, UpdateView):
    model = Award
    form_class = AwardForm
    template_name = 'movies/award_form.html'
    success_url = reverse_lazy('award_list')


class AwardDeleteView(LoginRequiredMixin, DeleteView):
    model = Award
    template_name = 'movies/award_confirm_delete.html'
    success_url = reverse_lazy('award_list')


class AwardDetailView(DetailView):
    model = Award
    template_name = 'movies/award_detail.html'
    context_object_name = 'award'


class MovieAwardCreateView(LoginRequiredMixin, CreateView):
    model = MovieAward
    form_class = MovieAwardForm
    template_name = 'movies/movieaward_form.html'

    def get_initial(self):
        initial = super().get_initial()
        movie_id = self.request.GET.get('movie')
        if movie_id:
            initial['movie'] = get_object_or_404(Movie, pk=movie_id)
        return initial

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        movie_id = self.request.GET.get('movie')
        if movie_id:
            context['movie'] = get_object_or_404(Movie, pk=movie_id)
        return context

    def form_valid(self, form):
        movie_id = self.request.GET.get('movie')
        form.instance.movie = get_object_or_404(Movie, pk=movie_id)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('movie_detail', kwargs={'pk': self.object.movie.pk})


class MovieAwardDeleteView(LoginRequiredMixin, DeleteView):
    model = MovieAward
    template_name = 'movies/movieaward_confirm_delete.html'
    success_url = reverse_lazy('movie_list')

    def get_success_url(self):
        movie_pk = self.get_object().movie.pk
        logger.debug(f"Redirecting to movie detail for movie ID: {movie_pk}")
        return reverse_lazy('movie_detail', kwargs={'pk': movie_pk})


class ReviewListView(ListView):
    model = Review
    template_name = 'movies/review_list.html'
    context_object_name = 'reviews'
    ordering = ['-created_at']


class ReviewCreateView(LoginRequiredMixin, CreateView):
    model = Review
    form_class = ReviewForm
    template_name = 'movies/review_form.html'
    success_url = reverse_lazy('review_list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ReviewUpdateView(LoginRequiredMixin, UpdateView):
    model = Review
    form_class = ReviewForm
    template_name = 'movies/review_form.html'
    success_url = reverse_lazy('review_list')


class ReviewDeleteView(LoginRequiredMixin, DeleteView):
    model = Review
    template_name = 'movies/review_confirm_delete.html'
    success_url = reverse_lazy('review_list')


def home(request):
    movies = Movie.objects.all()
    return render(request, 'home.html', {'movies': movies})

templates/movies/award_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container mt-5" style="max-width: 500px;">
<h1>{{ view.object.pk|yesno:"Edit Award,Add Award" }}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success mt-3">Save</button>
    </form>
</div>
{% endblock %}

templates/movies/award_list.html
{% extends 'base.html' %}
{% block content %}
<h1>Awards</h1>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th class="table-actions">Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for award in awards %}
            <tr>
                <td>{{ award.name }}</td>
                <td class="table-actions">
                    <a href="{% url 'award_edit' award.pk %}" class="btn btn-sm btn-primary">Edit</a>
                    <a href="{% url 'award_delete' award.pk %}" class="btn btn-sm btn-danger">Delete</a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
<a href="{% url 'award_add' %}" class="btn btn-success mb-3">Add Award</a>
{% endblock %}

templates/movies/cast_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<h1>Delete Cast</h1>
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete {{ object.person.first_name }} {{ object.person.last_name }} as {{ object.role_name }} in {{ object.movie.title }}?</p>
    <button type="submit" class="btn btn-sm btn-danger">Delete</button>
    <a href="{% url 'movie_list' %}" class="btn btn-sm btn-primary">Cancel</a>
</form>
{% endblock %}

templates/movies/cast_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container mt-5" style="max-width: 500px;">
<h1>{{ view.object.pk|yesno:"Edit Cast,Add Cast" }}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success mt-3">Save</button>
    </form>
</div>
{% endblock %}

templates/movies/genre_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container mt-5" style="max-width: 500px;">
<h1>{{ view.object.pk|yesno:"Edit Genre,Add Genre" }}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success mt-3">Save</button>
    </form>
</div>
{% endblock %}

templates/movies/movie_list.html
{% extends 'base.html' %}
{% block content %}
<h1>Movies</h1>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Title</th>
            <th class="table-actions">Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for movie in movies %}
            <tr>
                <td><a href="{% url 'movie_detail' movie.pk %}">{{ movie.title }} ({{ movie.release_year }})</a></td>
                <td class="table-actions">
                    <a href="{% url 'movie_edit' movie.pk %}" class="btn btn-sm btn-primary">Edit</a>
                    <a href="{% url 'movie_delete' movie.pk %}" class="btn btn-sm btn-danger">Delete</a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
<a href="{% url 'movie_add' %}" class="btn btn-success">Add Movie</a>
{% endblock %}

templates/movies/movieaward_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<h1>Delete Award</h1>
<p>Are you sure you want to delete the award "{{ object.award.name }}" 
    in the category "{{ object.category }}" for the movie "{{ object.movie.title }}"?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-sm btn-danger">Delete</button>
    <a href="{% url 'movie_detail' object.movie.pk %}" class="btn btn-sm btn-primary">Cancel</a>
</form>
{% endblock %}

templates/movies/movieaward_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container mt-5" style="max-width: 600px;">
<h1>Add Award to {{ movie.title }}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success mt-3">Save</button>
    </form>
</div>
{% endblock %}

templates/movies/person_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<h1>Delete Person</h1>
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete {{ object.first_name }} {{ object.last_name }}?</p>
    <button type="submit" class="btn btn-sm btn-danger">Delete</button>
    <a href="{% url 'person_list' %}" class="btn btn-sm btn-primary">Cancel</a>
</form>
{% endblock %}

templates/movies/person_detail.html
{% extends 'base.html' %}
{% block content %}
<h1>{{ person.first_name }} {{ person.last_name }}</h1>
<p><strong>Birth Date:</strong> {{ person.birth_date }}</p>
<p><strong>Death Date:</strong> {{ person.death_date|default:"N/A" }}</p>
<p><strong>Role:</strong> 
    {% if person.role == 'both' %}
        Actor, Director
    {% else %}
        {{ person.get_role_display }}
    {% endif %}
</p>
<h2>Movies</h2>
<ul>
    {% for movie in person.directed_movies.all %}
        <li>Directed: <a href="{% url 'movie_detail' movie.pk %}">{{ movie.title }}</a></li>
    {% endfor %}
    {% for cast in person.cast_set.all %}
        <li>Acted as {{ cast.role_name }} in: <a href="{% url 'movie_detail' cast.movie.pk %}">{{ cast.movie.title }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

templates/movies/person_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container mt-5" style="max-width: 500px;">
<h1>{{ view.object.pk|yesno:"Edit Person,Add Person" }}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success mt-3">Save</button>
    </form>
</div>
{% endblock %}

templates/movies/person_list.html
{% extends 'base.html' %}
{% block content %}
<h1>Persons</h1>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Role</th>
            <th class="table-actions">Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for person in persons %}
            <tr>
                <td><a href="{% url 'person_detail' person.pk %}">{{ person.first_name }} {{ person.last_name }}</a></td>
                <td>{{ person.display_role }}</td>
                <td class="table-actions">
                    <a href="{% url 'person_edit' person.pk %}" class="btn btn-sm btn-primary">Edit</a>
                    <a href="{% url 'person_delete' person.pk %}" class="btn btn-sm btn-danger">Delete</a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
<a href="{% url 'person_add' %}" class="btn btn-success">Add Person</a>
{% endblock %}

templates/movies/review_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<h1>Delete Review</h1>
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete this review?</p>
    <button type="submit" class="btn btn-sm btn-danger">Delete</button>
    <a href="{% url 'review_list' %}" class="btn btn-sm btn-primary">Cancel</a>
</form>
{% endblock %}

templates/movies/review_list.html
{% extends 'base.html' %}
{% block content %}
<h1>Reviews</h1>
<table class="table table-striped">
    <thead>
        <tr>
            <th>User</th>
            <th>Movie</th>
            <th>Rating</th>
            <th>Text</th>
            <th>Date</th>
            <th class="table-actions">Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for review in reviews %}
            <tr>
                <td>{{ review.user.username }}</td>
                <td><a href="{% url 'movie_detail' review.movie.pk %}">{{ review.movie.title }}</a></td>
                <td>{{ review.rating }} ⭐</td>
                <td class="review-text">{{ review.text }}</td>
                <td>{{ review.created_at|date:"Y-m-d H:i" }}</td>
                <td class="table-actions">
                    <a href="{% url 'review_edit' review.pk %}" class="btn btn-sm btn-primary">Edit</a>
                    <a href="{% url 'review_delete' review.pk %}" class="btn btn-sm btn-danger">Delete</a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
<a href="{% url 'review_add' %}" class="btn btn-success">Add Review</a>
{% endblock %}